---
engines:
  brakeman:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- config/
- db/
- spec/
- test/
- vendor/
- app/assets/javascripts/ekko-lightbox.js
- app/assets/javascripts/jquery.growl.js
- app/assets/stylesheets/bootstrap.min.css.map
- app/assets/stylesheets/ekko-lightbox.css