# Add configuration values here, as shown below.

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

flickr_api_key: YOUR_KEY
RECAPTCHA_SITE_KEY: YOUR_KEY
RECAPTCHA_SECRET_KEY: YOUR_KEY