# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 5

development:
  <<: *default
  database: flickr_dev
  username: root
  password: root

test:
  <<: *default
  database: flickr_test
  username: travis
  password: 

production:
  <<: *default
  host: us-cdbr-iron-east-04.cleardb.net
  database: heroku_598fed6e81b2f26
  username: be6ee530bb4e14
  password: cdfa2704