# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: mysql2
  encoding: utf8
  username: USERNAME
  password: PASSWORD
  host: HOST
  socket: /var/run/mysqld/mysqld.sock
  pool: 5

development:
  <<: *default
  database: flickr_dev

test:
  <<: *default
  database: flickr_test

production:
  <<: *default
  database: flickr_pro