# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: flickr_dev
  username:
  password:

test:
  <<: *default
  database: flickr_test
  username: postgres
  password: 

production:
  <<: *default
  database:
  username: 
  password: 